In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [125]:
df = pd.read_csv('Advertising.csv')

In [126]:
x = df.drop('sales' , axis=1)
y = df['sales']

In [127]:
from sklearn.preprocessing import PolynomialFeatures
poly_converter = PolynomialFeatures(degree=5 , include_bias=False)
poly_feature = poly_converter.fit_transform(x)

In [128]:
poly_feature.shape

(200, 55)

In [129]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#                                                  x feture but coverted to poly
x_train ,x_test ,y_train ,y_test = train_test_split(poly_feature,y , test_size=0.20 ,random_state=42)



In [130]:
x_train.shape

(160, 55)

In [131]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [132]:
scale_x_train = scaler.transform(x_train)

In [133]:
scale_x_test = scaler.transform(x_test)

In [134]:
scale_x_train[0]

array([-0.40424839, -1.02823707, -0.33767538, -0.6344003 , -0.78692467,
       -0.39505518, -0.93748644, -0.69943124, -0.48921405, -0.69558293,
       -0.6895931 , -0.47506758, -0.73434788, -0.55947409, -0.40692249,
       -0.80131077, -0.67967663, -0.56462234, -0.46093785, -0.67860173,
       -0.62017651, -0.48291554, -0.60798243, -0.47450701, -0.37293084,
       -0.64247143, -0.54606536, -0.43383357, -0.33793015, -0.69626049,
       -0.61456486, -0.54241571, -0.45542234, -0.37411883, -0.63370043,
       -0.55884175, -0.45431513, -0.52748585, -0.41469861, -0.33720372,
       -0.53323211, -0.44554605, -0.35351816, -0.27961681, -0.56788117,
       -0.50949441, -0.4274416 , -0.32817761, -0.25719371, -0.61903601,
       -0.55716194, -0.50767001, -0.44017978, -0.35817255, -0.28930697])

In [135]:
poly_feature[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05, 2.80327997e+09,
       4.60512747e+08, 8.43055082e+08, 7.56513769e+07, 1.38494055e+08,
       2.53539381e+08, 1.24277360e+07, 2.27513050e+07, 4.16505372e+07,
       7.62491316e+07, 2.04158375e+06, 3.73750252e+06, 6.84220038e+06,
       1.25259330e+07, 2.29310730e+07, 6.45034722e+11, 1.05963983e+11,
       1.93986974e+11, 1.74073818e+10, 3.18674821e+10, 5.83394116e+10,
       2.85962205e+09, 5.23507528e+09, 9.58378861e+09, 1.75449252e+10,
       4.69768420e+08, 8.59999329e+08, 1.57439031e+09, 2.88221718e+09,
       5.27643991e+09, 7.71718656e+07, 1.41277595e+08, 2.58635174e+08,
       4.73480266e+08, 8.66794561e+08, 1.58683026e+09])

In [136]:
from sklearn.linear_model import Ridge
Ridge_model = Ridge(alpha=10)
Ridge_model.fit(x_train,y_train)

c:\Users\mhija\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=2.31275e-25): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


Ridge(alpha=10)

In [137]:
test_ridge = Ridge_model.predict(x_test)

In [138]:
from sklearn.metrics import mean_absolute_error,root_mean_squared_error
 
MAE = mean_absolute_error(y_test , test_ridge)
RMSE = root_mean_squared_error(y_test,test_ridge)

In [139]:
MAE 

2.188425653811598

In [140]:
RMSE

8.859136185779043

In [141]:
from sklearn.linear_model import RidgeCV
ridge_cv = RidgeCV()

In [ ]:

from sklearn.linear_model import LassoCV
lasso_cv_model = LassoCV(eps  = 0.001, n_alphas = 100, cv = 5 ,max_iter=100000000)

In [143]:
lasso_cv_model.fit(x_train,y_train)

LassoCV(cv=5, max_iter=100000000)

In [144]:
lasso_cv_model.alpha_

np.float64(1654296776.7558851)

In [145]:
test_pred = lasso_cv_model.predict(x_test)
mae = mean_absolute_error(y_test,test_pred)
mae

2.4287905363364275

In [146]:
rmse = root_mean_squared_error(y_test,test_pred)
rmse

3.031425394312584

In [147]:
lasso_cv_model.coef_

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -3.39248988e-14,  4.49953416e-11,
       -5.15420257e-12,  1.63918076e-10,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [148]:
from sklearn.linear_model import ElasticNetCV
net_model = ElasticNetCV(l1_ratio=[.1 ,.5 ,.7, .9, .95, .99, 1]
                        ,eps=0.001 , n_alphas=100 ,max_iter=100000)

In [149]:
net_model.fit(x_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [150]:
# 1.0 means you your model 100% la ridge
net_model.l1_ratio_

np.float64(1.0)

In [153]:
net_model.alpha_

np.float64(1654296776.7558851)

In [152]:
# elactic model decied that lasso model is the best so it choose lasoo over ridge for regularaztion
lasso_cv_model.alpha_

np.float64(1654296776.7558851)